### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [smouksassi/coveffectsplot#3]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that your package somehow includes references to ggplot2 code from when it was build, either by reloading saved plot objects or by grabbing functions at build time. Please see https://www.tidyverse.org/blog/2022/09/playing-on-the-same-team-as-your-dependecy/ for some more info about why this can cause issues.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by smouksassi** [comment]
will look at this is it because I copied some functions from ggplot2, scales and ggstance ?

I import
Imports:
    colourpicker,
    egg,
    grid,
    ggplot2 (>= 3.3.2),

**Comment by thomasp85** [comment]
It is difficult to say - It might also be due to you using another extension package that causes the error.

The issue is:

```
Quitting from lines 268-328 (Pediatric_Cov_Sim.Rmd) 
  Error: processing vignette 'Pediatric_Cov_Sim.Rmd' failed with diagnostics:
  could not find function "rbind_dfs"
```

If you can pinpoint if this is an issue with another package you can ignore this issue (assuming the other package gets fixed)

**Comment by smouksassi** [comment]
ok thanks probably using  stat_quant_band from ggpmisc thanks !

**Comment by smouksassi** [comment]
closing as the package is working fine with  ggplot2 v3.4.0 I still have to implement linewidth for geom_pointrange
